UPDATE EMP SET FIRST_NAME = 'Tejas',LAST_NAME = 'Sutaria' WHERE EMP_ID =6;
UPDATE EMP SET FIRST_NAME = 'Hitesh',LAST_NAME = 'Yadav' WHERE EMP_ID =7;
UPDATE EMP SET FIRST_NAME = 'Sudhanshi',LAST_NAME = 'Salke' WHERE EMP_ID =8;

